value1 = int(input("Enter a number: "))
value2 = int(input("Enter a number: "))
sum = value1 + value2
minus = value1 - value2
multiple = value1 * value2
division = value1 / value2
print(f"The sum of {value1} and {value2} is => {sum}")
print(f"The difference between {value1} and {value2} is => {minus}")
print(f"The product of {value1} and {value2} is => {multiple}")
print(f"The quotient of {value1} and {value2} is => {division}")
